#theme = "catppuccin_mocha"
#theme = "catppuccin_macchiato"
theme = "mellow"
#theme = "rose_pine_dawn"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-u = ["half_page_up", "align_view_center"]
C-d = ["half_page_down", "align_view_center"]